services:
  - type: web
    name: grpc-greeter
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. greeter.proto"
    startCommand: "python server.py"
    envVars:
      - key: PORT
        value: 50051
